name: tts-stack
# TODO: https://docs.astral.sh/uv/guides/integration/docker/#configuring-watch-with-docker-compose
services:

#
# Dummy, not implemented yet
#
  tts-server:
    image: ghcr.io/matatonic/openedai-speech-min
    #image: thorsten-voice-openedai-speech:latest
    ports:
      - "8001:8000"
    volumes:
      - ./voices:/app/voices
      - ./config:/app/config
    environment:
      TTS_HOME: "/app/voices"
      HF_HOME: "/app/voices"
      PRELOAD_MODEL: "tts_models/de/thorsten/vits"
      LANGUAGE: "de_DE"
      VOICE: "thorsten_emotional-medium"
      PIPER_VOICE: "thorsten_emotional-medium"
#      VOICE: "torsten-low"
#      PIPER_VOICE: "torsten-low"
    command: ['python', 'speech.py', '--xtts_device', 'none']
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"


networks:
  servant-net:
    external: true
