name: servant-llm
services:

  ollama-llm:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
     - ollama-downloads:/root/.ollama
     - ./ollama-entrypoint.sh:/entrypoint.sh
    container_name: ollama-llm
    pull_policy: always
    tty: true
    restart: always
    environment:
     - OLLAMA_KEEP_ALIVE=24h
     - OLLAMA_HOST=0.0.0.0
     - OLLAMA_MODELS=/root/.ollama/models
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    environment:
      - OLLAMA_BASE_URL=http://ollama-llm:11434
      - WEBUI_AUTH=False
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-local:/app/backend/data
    networks:
      - servant-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  open-webui-local:
  ollama-downloads:

networks:
  servant-net:
    external: true
